package main.java.SMA;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import jade.gui.GuiAgent;
import jade.gui.GuiEvent;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class JfrmAgenteArchivo extends JFrame {

    private GuiAgent agent;

    private JButton seleccionarArchivoButton;
    private JButton iniciarProcesoButton;
    private JLabel path;
    private JPanel rootPanel;

    public JfrmAgenteArchivo(GuiAgent agent) {
        this.agent = agent;
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
        setTitle("Seleccionar archivo");
        seleccionarArchivoButton.addActionListener(actionEvent -> {
            String ruta;
            final JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos arff", "arff");
            chooser.setFileFilter(filter);
            chooser.showOpenDialog(rootPanel);
            ruta = chooser.getSelectedFile().toString();
            path.setText(ruta);
            System.out.format("JfrmAgenteArchivo: ruta del fichero seleccionado --> %s\n", ruta);
        });
        iniciarProcesoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                GuiEvent evento = new GuiEvent(this, 0);//el cero indica la accion a realizar, el 0 es para enviar
                agent.postGuiEvent(evento);
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), 0, 0));
        final JLabel label1 = new JLabel();
        label1.setText("Ruta:");
        rootPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rootPanel.add(panel1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        seleccionarArchivoButton = new JButton();
        seleccionarArchivoButton.setText("Seleccionar archivo");
        panel1.add(seleccionarArchivoButton);
        iniciarProcesoButton = new JButton();
        iniciarProcesoButton.setText("Iniciar proceso");
        panel1.add(iniciarProcesoButton);
        path = new JLabel();
        path.setText("");
        rootPanel.add(path, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(48, 18), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    public String obtenerRuta() {
        return path.getText();
    }
}
